export const voices = [
  { id: "Fritz-PlayAI", name: "Fritz", description: "Clear and precise" },
  { id: "Arista-PlayAI", name: "Arista", description: "Clear and articulate" },
  { id: "Atlas-PlayAI", name: "Atlas", description: "Strong and confident" },
  { id: "Basil-PlayAI", name: "Basil", description: "Warm and friendly" },
  { id: "Briggs-PlayAI", name: "Briggs", description: "Deep and authoritative" },
  { id: "Calum-PlayAI", name: "Calum", description: "Casual and conversational" },
  { id: "Celeste-PlayAI", name: "Celeste", description: "Smooth and professional" },
  { id: "Cheyenne-PlayAI", name: "Cheyenne", description: "Expressive and dynamic" },
  { id: "Chip-PlayAI", name: "Chip", description: "Energetic and upbeat" },
  { id: "Cillian-PlayAI", name: "Cillian", description: "Calm and soothing" },
  { id: "Deedee-PlayAI", name: "Deedee", description: "Friendly and approachable" },
  { id: "Gail-PlayAI", name: "Gail", description: "Warm and empathetic" },
  // { id: "Indigo-PlayAI", name: "Indigo", description: "Neutral and balanced" },
  // { id: "Mamaw-PlayAI", name: "Mamaw", description: "Gentle and nurturing" },
  // { id: "Mason-PlayAI", name: "Mason", description: "Strong and reliable" },
  // { id: "Mikail-PlayAI", name: "Mikail", description: "Calm and authoritative" },
  // { id: "Mitch-PlayAI", name: "Mitch", description: "Friendly and casual" },
  // { id: "Quinn-PlayAI", name: "Quinn", description: "Neutral and clear" },
  // { id: "Thunder-PlayAI", name: "Thunder", description: "Bold and powerful" },
  // { id: "Ahmad-PlayAI", name: "Ahmad", description: "Clear and articulate (Arabic)" },
  // { id: "Amira-PlayAI", name: "Amira", description: "Smooth and professional (Arabic)" },
  // { id: "Khalid-PlayAI", name: "Khalid", description: "Strong and confident (Arabic)" },
  // { id: "Nasser-PlayAI", name: "Nasser", description: "Deep and authoritative (Arabic)" }
];
